### ISSUE TITLE
OPCUA.Common doesn't load nugets

### ISSUE THREAD

**Issue by mpostol** [mpostol/ASMD#250]
## Describe the bug

There is a wrong path in the project. The project must be compiled from the local solution to load the NuGet packages. The `.gitmodules` must be reviewed.

## To Reproduce

Load the repository from scratch or clean up before compiling.  There are compilation errors.

## Expected behavior

After cleaning the repository the solution must be error-free.

**Comment by mpostol** [comment]
Follow the documentation: 

- <https://git-scm.com/docs/gitmodules>
- [Working with submodules](https://github.blog/2016-02-01-working-with-submodules/)

**Comment by mpostol** [comment]
Workaround: the project must be built separately.  It must not be fixed. After replacing it with the reference to the NuGet package the problem will disappear.
